##
# Azure Pipeline CI build and PR build

# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
resources:
  repositories:
    - repository: pytool_extensions
      type: github
      name: tianocore/edk2-pytool-extensions
      ref: refs/heads/master
      endpoint: tianocore

# trigger on master for CI and all PRs for master
trigger: 
- master

pr: 
- master

jobs:
- template: azure-pipelines/templates/build-test-job.yml@pytool_extensions
  parameters:
    vm_image: 'windows-latest'
    root_package_folder: "edk2toollib"
    name: 'windows'
    codecov_enabled: true

- template: template/auto-doc-job.yml # make sure this runs after this
  parameters:
    vm_image: 'windows-latest'
